PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 18.208.46.151.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    GHE:
    - Name: GitCorp
      Url: https://git.corp.adobe.com/api/v3/
    Global:
      EnvVars:
        DOCKER_REGISTRY: docker2-adobe-launch-release-local.dr-uw2.adobeitc.com
        TILLER_NAMESPACE: kube-system
prow: {}
